# Generated by Django 3.0.2 on 2020-01-13 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware_Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firmware_Version_id', models.CharField(blank=True, default=' -- ', max_length=100)),
                ('Firmware_version_number', models.CharField(blank=True, default=' -- ', max_length=100)),
                ('device_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device')),
            ],
        ),
    ]
