# Generated by Django 3.0.2 on 2020-01-13 22:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_api', '__first__'),
        ('device', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_name', models.CharField(blank=True, default='', max_length=100)),
                ('Start_Time', models.TimeField(default=django.utils.timezone.now)),
                ('End_Time', models.TimeField(default=django.utils.timezone.now)),
                ('device_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device')),
                ('patient_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.Profile')),
            ],
        ),
    ]
