# Generated by Django 3.0.2 on 2020-02-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200207_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_file_id',
            field=models.CharField(default='0001', max_length=50, unique=True),
        ),
    ]
