# Generated by Django 3.0.2 on 2020-02-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200207_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_file_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
