# Generated by Django 3.0.2 on 2020-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200219_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='End_Time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='Start_Time',
            field=models.BigIntegerField(),
        ),
    ]
