# Generated by Django 3.0.2 on 2020-03-10 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_patient_patient_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0004_auto_20200203_0643'),
        ('data', '0007_auto_20200306_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='File',
            field=models.FileField(upload_to='DJANGO_SERVER_FILES/Raw_Files/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>'),
        ),
        migrations.CreateModel(
            name='Data_filtered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file_id', models.CharField(max_length=50, unique=True)),
                ('File', models.FileField(upload_to='DJANGO_SERVER_FILES/Filtered_Files/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>')),
                ('Start_Time', models.BigIntegerField()),
                ('End_Time', models.BigIntegerField()),
                ('device_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device')),
                ('patient_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
