# Generated by Django 3.0.2 on 2020-03-10 14:52

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200310_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='File',
            field=models.FileField(upload_to=data.models.user_directory_path),
        ),
    ]
