# Generated by Django 3.0.2 on 2020-03-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200310_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='File',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data_filtered',
            name='File',
            field=models.CharField(max_length=100),
        ),
    ]
