# Generated by Django 3.0.2 on 2020-03-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20200312_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='BD_FE',
            fields=[
                ('Parent_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Data_filtered')),
                ('File', models.CharField(max_length=100)),
            ],
        ),
    ]
