# Generated by Django 3.0.2 on 2020-06-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_bd_fe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_fe',
            name='File',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='data',
            name='File',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='data_filtered',
            name='File',
            field=models.CharField(max_length=300),
        ),
    ]
