# Generated by Django 3.0.2 on 2020-01-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, default='', max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('Mac_id', models.CharField(blank=True, default='', max_length=100)),
                ('Num_of_Leads', models.IntegerField(default=12)),
            ],
        ),
    ]
