# Generated by Django 3.0.2 on 2020-01-13 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_api', '__first__'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_device_mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.Profile')),
            ],
        ),
    ]
