# Generated by Django 3.0.2 on 2020-03-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20200203_0643'),
        ('patient', '0005_remove_patient_patient_id'),
        ('misc', '0003_user_patient_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_device_mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device')),
                ('patient_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
